# Copyright 2019-2021 Tauri Programme within The Commons Conservancy
# SPDX-License-Identifier: Apache-2.0
# SPDX-License-Identifier: MIT

name: clippy

on:
  push:
    branches:
      - dev
    paths:
      - '.github/workflows/clippy.yml'
      - 'packages/cli/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
  pull_request:
    paths:
      - .github/workflows/clippy.yml
      - packages/cli/**
      - Cargo.lock
      - Cargo.toml

concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
   cancel-in-progress: true

jobs:
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy --all-targets --all-features -- -D warnings